home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index')
]

python_webapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
# from django.contrib.auth.views import login

urlpatterns = [
    url(r'^\Z', include('home.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^ontogen/', include('ontogen.urls')),
    url(r'^sqrt/', include('sqrt_platform.urls')),
    # url(r'^accounts/login/$', login, {'template_name': 'admin/login.html'})
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sqrt_platform/urls.py
from django.utils import timezone
from django.conf.urls import url
from django.views.i18n import JavaScriptCatalog
# from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.views import login
from django.views.decorators.http import last_modified

from . import views

# app_name is used to refence urls in template tags
app_name = 'sqrt_platform'

# patterns describe how app dispathes http-requests
# details: https://docs.djangoproject.com/en/1.11/topics/http/urls/
urlpatterns = [
    # js-catalog can be used to access translation fucntions on client-side
    url(r'^jsi18n/$',
        JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^$',
        views.index, name='index'),
    url(r'^lang/(?P<locale>.+)/$',
        views.index_locale, name='index_locale'),
    url(r'^calc/$',
        views.get_sqrt, name='get_sqrt'),
    url(r'^calc_ex/$',
        views.get_sqrt_ex, name='get_sqrt_ex'),
    url(r'^docs/$',
        views.documentation, name='documentation'),
]

sqrt_platform/models.py
from django.db import models

# Create your models here.

sqrt_platform/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.utils import translation
from django.utils.translation import activate
from django.utils.translation import ugettext as _

from .core import sqrt
from .core import wolfram
# Create your views here.

LANGUAGES_CONTEXT = {'available_languages': ['ru', 'en', 'es', 'zh-hant']}


def ajax_only(function):
    """Decorator for views that checks if requests was send via ajax"""
    def function_wrapper(*args, **kwargs):
        request = args[0]
        if not request.is_ajax():
            raise Http404
        return function(*args, **kwargs)
    return function_wrapper


def index(request):
    return render(request, 'sqrt_platform/index.html', LANGUAGES_CONTEXT)


def index_locale(request, locale):
    activate(locale)
    request.session[translation.LANGUAGE_SESSION_KEY] = locale
    return render(
        request,
        'sqrt_platform/redir_to_index.html',
        {'redirect': request.GET.get('redir', '/')})


def documentation(request):
    return render(
        request,
        'sqrt_platform/documentation.html', LANGUAGES_CONTEXT)


@ajax_only
def get_sqrt(request):
    response = HttpResponse()
    response['debug'] = request.POST

    if request.POST.get('number') == "":
        response.write(_('Number is required'))
    else:
        try:
            number = request.POST.get('number', None)
            if (request.POST.get('use_precision', None)):
                prec = request.POST.get('precision', None)
            else:
                prec = None
            result = sqrt.get_sqrt(number, prec)
            response.write(result)
        except Exception as e:
            response.write(str(e))
    return response


@ajax_only
def get_sqrt_ex(request):
    response = HttpResponse()
    response['debug'] = request.POST

    if request.POST.get('number') == "":
        response.write(_('Expression is required'))
    else:
        try:
            expression = request.POST.get('number', None)
            result = wolfram.get_sqrt('sqrt({})'.format(expression))
            response.write(result)
        except Exception as e:
            response.write(str(e))
    return response

sqrt_platform/templates/sqrt_platform/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% trans "Square root calculator" %}</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'sqrt_platform/style.css' %}" />
    <!--<script type="text/javascript" src="{% url 'sqrt_platform:javascript-catalog' %}"></script>-->
    <script type="text/javascript" src="{% static 'ontogen/tree/res/lib/jquery/jquery.min.js' %}"></script>
    {% block head %}
    {% endblock %}
    <script>
        var change_locale = function() {
            window.location.replace('{% url "sqrt_platform:index" %}lang/' + $("#language").val() + '/?redir=' + window.location.href);
        };

        var timer;

        $(document).on({
            ajaxStart: function() { 
                timer && clearTimeout(timer);
                timer = setTimeout(function()
                {
                     $('body').addClass("loading");
                },
                1000);
            },
            ajaxStop: function() { 
                clearTimeout(timer);
                $('body').removeClass("loading"); 
            }    
        });
    </script>
</head>
<body>
    <div id="container">
        <div id="header">
            <div id="branding">
                <h1 id="site-name"><a href="{% url 'sqrt_platform:index' %}">GrootSQRT: {% trans "Square root calculator" %}</a></h1>
            </div>
            <div id="user-tools">
                <span class="references">
                    <a href="{% url 'sqrt_platform:documentation' %}">{% trans "Documentation" %}</a>
                    | {% trans "Choose language" %}:
                </span>
                <select id="language" onchange="change_locale()">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_language_info_list for available_languages as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                            {{ language.name_local }} ({{ language.code }})
                        </option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div id="navigation-block">
            {% block navigation %}
            {% endblock %}
        </div>
        <div id="content" class="colM">
            {% block content %}
            {% endblock %}
        </div>
        <div id="footer"></div>
    </div>
    <div class="modal"><!-- Place at bottom of page --></div>
</body>
</html>

sqrt_platform/templates/sqrt_platform/documentation.html
{% extends 'sqrt_platform/base.html' %}

{% load i18n static %}

{% block content %}
<h1>{% trans "Documentation" %}</h1>
<div style="text-align: justify;">
    {% blocktrans %}
    <p>
        Enter the number or mathematical expression whose square root you want to find in the “Number/Expression” field. It can be an integer or a fractional number, a large number, a complex number.
        <br/>Terms of use:
        <ul>
            <li>Use the symbol "." аs the separator of the whole and fractional part of the number.</li>
            <li>Use "i" as the imaginary unit in the complex number.</li>
            <li>It is possible to use in the expression the signs of arithmetic operations, the symbol "^" or "**" for exponentiation, parentheses, sqrt (expression) - square root, abs (expression) - module, as well as various trigonometric functions.</li>
        </ul>
    </p>
    <p>
        If you want to set the precision, open the menu “Show precision” and enter amount of decimal places in the answer.
    </p>
    <p>
        Click the "Calculate" button to get the square root of the number and "Calculate expression" to get the square root of the expression. The resulting square root will be in the text field below the button. If no response was received, check the original data. If it is true, try again. If this problem persists, contact the support via <a href="http://sqrtme.mybb.ru/">forum</a> or by e-mail <a href="mailto:groot.sqrt@mail.ru" target="_top">groot.sqrt@mail.ru</a>.
    </p>
    {% endblocktrans %}
</div>
{% endblock %}

sqrt_platform/templates/sqrt_platform/index.html
{% extends 'sqrt_platform/base.html' %}

{% load i18n static %}
{% get_language_info for get_current_language as lang %}

{% block content %}
<div class="calc-block">
  <form id="form" method="post" action="">
    {% csrf_token %}
    <fieldset class="module aligned ">
      <div id="number-block" class="form-row">
        <label>{% trans "Number / Expression" %}:</label> <input type="text" id="num" name="number" required/>
      </div>
      <div id="precision-block" class="form-row" hidden>
        <label>{% trans "Precision" %}:</label>
        <input type="number" min="1" max="1000" step="1" id="precin" value="16" name="precision" onkeyup="this.value = minmax(this.value, 1, 1000)"/>
        <input type="checkbox" id="use_precision" name="use_precision" hidden/>
      </div>
      <div class="form-row">
        <div style="margin-top: 10px">
          <textarea id="answ" readonly></textarea>
        </div>
        <div id="test">
        </div>
      </div>
      <div class="help">
         <a href="http://sqrtme.mybb.ru">{% trans "Having troubles with our app? Visit our forum!" %}</a>
      </div>
      <div class="submit-row" style="margin-top: 10px">
        <input type="button" id="solve" value='{% trans "Calculate" %}'/>
        <input type="button" id="solve_ex" value='{% trans "Calculate expression" %}'/>
        <input type="button" id="precision_toggle" value='{% trans "Show precision" %}'/>
      </div>
    </fieldset>
  </form>
</div>
{% endblock %}

{% block head %}
<script src="https://rawgit.com/jackmoore/autosize/master/dist/autosize.min.js"></script>
<script>
  function post_form(post_url)
  {
    $.ajax({
        type: 'POST',
        url: post_url,
        data: $('#form').serialize(),
        // global: false,
        success: function(data, textStatus, request) {
          var output = document.getElementById('answ')
          output.value = request.responseText;
          autosize.update(output);
        },
        error: function(data, textStatus, request) {
          alert(request.responseText)
        }
      });
  }

  var get_sqrt = function () {
    post_form('{% url "sqrt_platform:get_sqrt" %}');
  };

  var get_sqrt_ex = function () {
    post_form('{% url "sqrt_platform:get_sqrt_ex" %}');
  }

  var toggle_precision_block = function() {
    prec_block = document.getElementById("precision-block")
    button = document.getElementById("precision_toggle")
    check = document.getElementById("use_precision")

    prec_block.hidden = !prec_block.hidden;
    check.checked = !check.checked;

    if (prec_block.hidden) {
      button.value = '{% trans "Show precision" %}'
    } else {
      button.value = '{% trans "Hide precision" %}'
    }
  }

  window.onload = function() {
    document.getElementById("solve").onclick = get_sqrt;
    document.getElementById("solve_ex").onclick = get_sqrt_ex;
    document.getElementById("precision_toggle").onclick = toggle_precision_block;

    autosize(document.getElementById('answ'));
  }

  function minmax(value, min, max) 
  {
      if(parseInt(value) < min || isNaN(parseInt(value))) 
          return min; 
      else if(parseInt(value) > max) 
          return max; 
      else return value;
  }
</script>
{% endblock %}

sqrt_platform/templates/sqrt_platform/redir_to_index.html
<script>
    window.location.replace('{{ redirect }}');
</script>