home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index')
]

ontogen/urls.py
from django.utils import timezone
from django.conf.urls import url
from django.views.i18n import JavaScriptCatalog
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.views import login
from django.views.decorators.http import last_modified

from . import views

app_name = 'ontogen'
last_modified_date = timezone.now()

urlpatterns = [
    url(r'^jsi18n/$',
        last_modified(lambda req, **kw: last_modified_date)
        (JavaScriptCatalog.as_view()), name='javascript-catalog'),
    url(r'^$',
        views.index, name='index'),
    url(r'^result/$',
        views.generate_ont, name='generate'),
    url(r'^history/$',
        views.usage_history, name='usage_history'),
    url(r'^tree/$',
        views.get_tree_data, name='get_tree'),
    url(r'^pattern/(?P<pk>[0-9]+)/$',
        views.PatternDetailView.as_view(), name='pattern_view'),
    url(r'^pattern/add/$',
        views.PatternCreateView, name='pattern_add'),
    url(r'^pattern/(?P<pattern_id>[0-9]+)/edit/$',
        views.PatternUpdateView, name='pattern_update'),
    url(r'^pattern/(?P<pk>[0-9]+)/delete/$',
        views.PatternDeleteView.as_view(), name='pattern_delete'),
    url(r'^instruction/(?P<pk>[0-9]+)/$',
        views.InstructionDetailView.as_view(), name='instruction_view'),
    url(r'^instruction/add/$',
        views.InstructionCreateView.as_view(
            # Translators: This string represents view's header
            extra_context={'header': _('Add new instruction')}),
        name='instruction_add'),
    url(r'^instruction/(?P<pk>[0-9]+)/edit/$',
        views.InstructionUpdateView.as_view(
            # Translators: This string represents view's header
            extra_context={'header': _('Edit instruction')}),
        name='instruction_update'),
    url(r'^instruction/(?P<pk>[0-9]+)/delete/$',
        views.InstructionDeleteView.as_view(), name='instruction_delete'),
    url(r'^login/$', login,
        {'template_name': 'ontogen/login.html'}, name='login'),
    url(r'^ok/', views.ok_response, name='ok'),
    url(r'^generate/$', views.generate_page, name='generate_new'),
    url(r'^generate_subject/$', views.generate_subject_ont, name='generate_subject'),
    url(r'^generate_task/$', views.generate_task_ont, name='generate_task'),
    url(r'^populate_subject_with_image/$', views.populate_subject_with_image, name='populate_subject_with_image'),
    url(r'^resources/images/(?P<pk>[0-9]+)/$', views.get_file_from_repository, name='get_image'),

    url(r'^resources/framesets/(?P<frameset_id>[0-9]+)/$', views.get_frameset, name='get_frameset'),
    url(r'^resources/framesets/frame/(?P<pk>[0-9]+)/$', views.get_file_from_repository, name='get_frameset'),
    url(r'^resources/models/(?P<pk>[0-9]+)/$', views.get_file_from_repository, name='get_model'),

    # url(r'^test_request/$', views.get_test_request, name='some_name'),
    # url(r'^test_upload/$', views.post_upload_image, name='test_upload'),

    url(r'^framesets/$', views.get_framesets, name='frameset_get_all'),
    url(r'^frameset/add/$', views.add_frameset_view, name='frameset_add'),
    url(r'^frameset/(?P<pk>[0-9]+)/$', views.FramesetDetailView.as_view(), name='frameset_detail'),
    url(r'^frameset/(?P<pk>[0-9]+)/delete/$', views.FramesetDeleteView.as_view(), name='frameset_delete'),

    url(r'^populate_task_with_method/$', views.populate_task_with_method, name='populate_task_with_method')
]

python_webapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
# from django.contrib.auth.views import login

urlpatterns = [
    url(r'^\Z', include('home.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^ontogen/', include('ontogen.urls')),
    url(r'^sqrt/', include('sqrt_platform.urls')),
    # url(r'^accounts/login/$', login, {'template_name': 'admin/login.html'})
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ontogen/models.py
import re
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _, ugettext
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType

from .core.Parser.PatternReader import PatternReader


class Instruction(models.Model):
    instruction_label = models.CharField(_("instruction label"), max_length=50)
    instruction_text = models.TextField(_("instruction text"))
    
    instruction_content = RichTextField(_("instruction content"), default='')

    def __str__(self):
        return self.instruction_label

    def get_json(self):
        return {
            "id": "instruction" + str(self.id),
            "type": "instruction",
            "text": str(self),
        }

    @classmethod
    def get_json_all(cls):
        return {
            "text": ugettext("Instructions"),
            "type": "instruction-container",
            "children": [
                item.get_json() for item in Instruction.objects.all()
            ],
            "li_attr": {
                "class": "select-single capitalized container"
            }
        }


class Pattern(models.Model):
    pattern_label = models.CharField(_("pattern label"), max_length=50)
    pattern_text = models.CharField(_("pattern text"), max_length=200)

    NONE = None
    CONCEPT = 'concept'
    RELATION = 'relation'
    ELEMENT_TYPES = (
        (NONE, '-'),
        (CONCEPT, _('Concept')),
        (RELATION, _('Relation')),
    )

    MAPPING_SEPARATOR = ';;;'

    extracted_elements_type = \
        models.CharField(
            _("extracted elements type"), max_length=50,
            choices=ELEMENT_TYPES, default=CONCEPT)

    def __str__(self):
        return self.pattern_label

    def get(self):
        reader = PatternReader()
        regex = reader.parse_pattern(self.pattern_text)
        pattern_mappings = self.MAPPING_SEPARATOR.join(
            [mapping.get() for mapping in self.mappings.all()])
        if self.extracted_elements_type is not None:
            pattern_mappings += self.MAPPING_SEPARATOR \
                + 'type=' + self.extracted_elements_type
        return {
            'name': self.pattern_label,
            'regex': regex,
            'mappings': pattern_mappings}

    def get_json(self):
        return {
            "id": "pattern" + str(self.id),
            "type": "pattern",
            "text": str(self)
        }

    @classmethod
    def get_json_all(cls):
        return {
            "text": ugettext("Patterns"),
            "type": "pattern-container",
            "children": [
                item.get_json() for item in Pattern.objects.all()
            ],
            "li_attr": {
                "class": "select-multiple capitalized container"
            }
        }


class Mapping(models.Model):
    pattern = models.ForeignKey(Pattern, on_delete=models.CASCADE,
                                related_name='mappings')
    mapping_label = models.CharField(_("mapping label"), max_length=50)
    mapping_value = models.CharField(_("mapping value"), max_length=100)

    def __str__(self):
        return self.mapping_label.replace('_', ' ')

    def get(self):
        return self.mapping_label + '=' + self.mapping_value


class Ontology(models.Model):
    name = models.CharField(_("ontology name"), max_length=50)
    ont = models.TextField()

    SUBJECT = 'subject'
    APPLIED = 'applied'
    ONTOLOGY_TYPES = (
        (SUBJECT, _('subject ontology')),
        (APPLIED, _('applied ontology')),
    )

    ontology_type = \
        models.CharField(
            _("ontology type"), max_length=50,
            choices=ONTOLOGY_TYPES)


def get_sentinel_user():
    return User.objects.get_or_create(username='deleted')[0]


class HistoryRecord(models.Model):
    datetime = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.SET(get_sentinel_user))
    instruction = models.ForeignKey(Instruction, on_delete=models.SET_NULL, null=True)
    patterns = models.ManyToManyField(Pattern)
    results = models.ManyToManyField(Ontology)

    def __str__(self):
        return '[' + str(self.datetime) + '] ' + self.user.username

    class Meta:
        ordering = ('datetime', 'user')


class AbstractGranule(models.Model):
    name = models.CharField(max_length=200)
    # meta_data = JSONField()

    CONTAINER_TYPE = 'cont'
    TERMINAL_TYPE = 'term'

    GRANULE_TYPES = (
        (None, '-'),
        (CONTAINER_TYPE, _('Container')),
        (TERMINAL_TYPE, _('Terminal')),
    )

    type = models.CharField(max_length=4, choices=GRANULE_TYPES, default=TERMINAL_TYPE)

    child_granules = models.ManyToManyField("self")

    class Meta:
        abstract = True

    def get_elements(self):
        if self.type == self.TERMINAL_TYPE:
            return [str(x) for x in self.elements.all()]
        else:  # self is a container
            elements = []

            for child in self.child_granules.all():
                elements.append(child.get_elements())

            return elements

    def __str__(self):
        return self.name


class GranuleItem(models.Model):

    url = models.CharField(max_length=200)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    granule = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.url


class FramesetGranule(AbstractGranule):
    first_frame = models.CharField(max_length=200)
    last_frame = models.CharField(max_length=200)

    elements = GenericRelation(GranuleItem)

    def to_json(self):
        return {
            'first': self.first_frame,
            'last': self.last_frame,
            'elements': self.get_elements()
        }

    def get_tree_json(self):
        return {
            "id": "frameset" + str(self.id),
            "type": "frameset",
            "text": str(self),
            "li_attr": {
                "class": "no-select"
            }
        }

    @classmethod
    def get_tree_json_all(cls):
        return {
            "text": ugettext("Framesets"),
            "type": "frameset-container",
            "children": [
                item.get_tree_json() for item in cls.objects.all()
            ],
            "li_attr": {
                "class": "select-multiple capitalized container"
            }
        }

ontogen/forms.py
from django import forms
from . import models


class PatternForm(forms.ModelForm):
    class Meta:
        model = models.Pattern
        fields = ['pattern_label', 'pattern_text', 'extracted_elements_type']

ontogen/templates/ontogen/base.html
{% load static %} {% load i18n %}
<!DOCTYPE html>
<html>

<head>
    <title>Ontology Generator | VReutov</title>
    <script type="text/javascript" src='{% static 'jquery/dist/jquery.js' %}'></script>
    <script type="text/javascript" src='{% static 'underscore/underscore-min.js' %}'></script>
    <script type="text/javascript" src='{% static 'bootstrap/dist/js/bootstrap.min.js' %}'></script>
    <link rel="stylesheet" href='{% static 'bootstrap/dist/css/bootstrap.min.css' %}'>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css"/>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'ontogen/custom_base.css' %}"/>
    <link rel="shortcut icon" href="{% static 'ontogen/favicon.ico' %}">
    {% block head %} {% endblock %}
</head>

<body>
<div class="body-box">
    <div class="header-row">
        <div id="branding">
            <h1>
                <a href="{% url 'ontogen:index' %}">OntoGen</a>
            </h1>
        </div>
        <div id="user-block">
            {% comment %}Translators: User greetings{% endcomment %} {% trans "Welcome" %},
            {% if user.is_authenticated %}
                <strong>{{ user }}</strong>
            {% else %}
                <strong>{% trans "guest" %},</strong>
            {% endif %}
        </div>
    </div>
    {# Important to keep navigation block empty by default! #}
    <div id="navigation-block">{% block navigation %}{% endblock %}</div>
    <div class="content-row">
        {% block content %} {% endblock %}
    </div>
    <div class="footer-row">
    </div>
</div>
</body>

</html>

ontogen/templates/ontogen/frameset_create.html
{% load i18n %}
<div class="bot-modal-header">
    <span class="mod-close" id="modal-close">&times;</span>
    <h1>Добавить новый набор кадров</h1>
</div>
<form action="" method="post" id="form">
    {% csrf_token %}
    <fieldset class="aligned">
        <div class="form-row">
            <label for="frameset-name">Имя:</label>
            <input id="frameset-name" name="name" type="text" class="full-width" value="{{ name }}">
        </div>
        <div class="form-row">
            <input id="frameset-files" name="files" type="file" multiple>
            <ul class="errorlist">
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    </fieldset>
    <div class="submit-row">
        <input id="submit-form-button" type="button" value="{% trans "Save" %}" class="default"/>
    </div>
</form>

<script>
    $("#frameset-files").fileinput({
        language: 'ru',
        showUpload: false,
        allowedFileTypes: ["image"],
        initialPreviewShowDelete: true,
        removeFromPreviewOnError: true,
        layoutTemplates: {
            main1: "{preview}\n" +
            "<div class=\'input-group {class}\'>\n" +
            "   <div class=\'input-group-btn\ input-group-prepend'>\n" +
            "       {browse}\n" +
            "       {upload}\n" +
            "       {remove}\n" +
            "   </div>\n" +
            "   {caption}\n" +
            "</div>"
        },
        msgPlaceholder: 'Файлы не выбраны',
        fileActionSettings: {
            showRemove: true,
            showUpload: false,
            showZoom: false,
            showDrag: true
        }
    });
</script>

ontogen/templates/ontogen/framesetgranule_detail.html
{% load i18n %}
<div class="bot-modal-header">
    <span class="mod-close" id="modal-close">&times;</span>
    <h1>{{ framesetgranule.name }}</h1>
</div>
<fieldset class="aligned">
    <div class="form-row">
        <div>
            <div class="list-group">
                <a href="#" class="list-group-item active">
                    <span class="badge">{{ framesetgranule.elements.count }}</span>
                    Frames
                </a>
                {% for frame in framesetgranule.elements.all %}
                    <a href="#" class="list-group-item">{{ frame.url }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</fieldset>

ontogen/templates/ontogen/index.html
{% extends 'ontogen/base.html' %}

{% load i18n static %}

{% block navigation %}
    <ul class="nav nav-pills">
        <li class="active">
            <a href="#">{% trans "Ontology generation" %}</a>
        </li>
        <li>
            <a href="{% url 'ontogen:usage_history' %}">{% trans "Usage history" %}</a>
        </li>
    </ul>
{% endblock %}

{% block content %}
    <div id="content-main">
        <form action="{% url 'ontogen:generate_new' %}" method="post" id="user_form">
            {% csrf_token %}
            <h1 style="color: DimGray ">{% trans "Repository tree" %}</h1>
            <div class="help-box" style="float: right">
                <!--<h3>Select resources you want to use and click the "Generate ontology" button</h3>-->
            </div>
            {% if messages %}
                <ul class="errorlist">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <div id="tree"></div>
            <div class="submit-row">
                {% comment %}Translators: Button caption{% endcomment %}
                <input id="submit-button" type="submit" value="{% trans "Generate Ontologies" %}" class="default"
                       name="_generate"/>
            </div>
        </form>
        <div id="modal-info" class="bot-modal">
            <div id="modal-content" class="bot-modal-content"></div>
        </div>
    </div>
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'jstree/dist/themes/default/style.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'jstree-bootstrap-theme/dist/themes/proton/style.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'ontogen/tree/tree_style.css' %}"/>
    <link rel="stylesheet" href="{% static 'ontogen/custom_admin.css' %}"/>
    <link rel="stylesheet" href="{% static 'ontogen/modal.css' %}"/>

    <script type="text/javascript" src="{% static 'jstree/dist/jstree.min.js' %}"></script>
    <script type="text/javascript" src="{% url 'ontogen:javascript-catalog' %}"></script>
    <script type="text/javascript" src="{% static 'ontogen/tree/tree.js' %}"></script>
    <script type="text/javascript" src="{% static 'ontogen/tree/tree_functions.js' %}"></script>

    <link href="{% static 'bootstrap-fileinput/css/fileinput.min.css' %}" media="all" rel="stylesheet" type="text/css" />
    <script src="{% static 'bootstrap-fileinput/js/fileinput.min.js' %}"></script>
    <script src="{% static 'bootstrap-fileinput/js/locales/ru.js' %}"></script>

    <script>
        $(document).ready(function () {
            $('#user_form').submit(function () {
                var checked_ids = $("#tree").jstree("get_checked", null, true);
                // append data to post
                $(this).append('<input type="hidden" id="checked_ids" name="checked_ids" value="' + checked_ids + '"/>');
            });

            window.onclick = function (event) {
                if (event.target === document.getElementById('modal-info')) {
                    event.target.style.display = "none";
                }
            };
        });
    </script>
{% endblock %}

ontogen/templates/ontogen/instruction_detail.html
{% load i18n %}
<div class="bot-modal-header">
    <span class="mod-close" id="modal-close">&times;</span>
    <h1>{{ instruction.instruction_label }}</h1>
</div>
<fieldset class="aligned">
    <div class="form-row">
        <div>
            {{ instruction.instruction_content|safe }}
            <!-- <textarea readonly name="_text">{{ instruction.instruction_text }}</textarea> -->
        </div>
    </div>
</fieldset>

ontogen/templates/ontogen/instruction_form.html
{% load i18n %}
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>

<style>
#id_instruction_label {
    width : calc(100% - 170px);
    box-sizing: border-box;
}

[data-field-id="id_instruction_content"] {
    width : 100%;
    box-sizing: border-box;
}
</style>
<div class="bot-modal-header">
    <span class="mod-close" id="modal-close">&times;</span>
    <h1>{{ header }}</h1>
</div>
<form action="" method="post" id="form">
    {% csrf_token %}
    {{ form.management_form }}
    {{ form.non_field_errors }}
    <fieldset class="module aligned ">
    {% for field in form %}
        <div class="form-row">
            <div>
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </div>
        </div>
    {% endfor %}
    </fieldset>
    <div class="submit-row">
        <input id="submit-form-button" type="button" value="{% trans "Save" %}" class="default"/>
    </div>
</form>

ontogen/templates/ontogen/pattern_confirm_delete.html
{% load i18n %}
<div class="bot-modal-header">
    <span class="mod-close" id="modal-close">&times;</span>
    <h1>Are you sure you want to delete pattern "{{ object }}"?</h1>
</div>
<form action="" method="post" id="form">
    {% csrf_token %}
    <div class="submit-row" style="margin: 0">
        <input id="submit-form-button" type="button" value="{% trans "Confirm" %}" class="default"/>
    </div>
</form>

ontogen/templates/ontogen/pattern_detail.html
{% load i18n %}
{% load ontogen_extras %}

<div class="bot-modal-header">
    <span class="mod-close" id="modal-close">&times;</span>
    <h1>{{ pattern.pattern_label }}</h1>
</div>
<fieldset class="module aligned ">
    <div class="form-row">
        <div>
            <label for="id_pattern_text" class="capitalized">{{ pattern|field:"pattern_text"|verbose_name }}:</label>
            <input class="vTextField" id="id_pattern_text" type="text" value="{{ pattern.pattern_text }}" readonly/>
        </div>
    </div>
    <div class="form-row">
        <div>
            <label for="id_pattern_field" class="capitalized">{{ pattern|field:"extracted_elements_type"|verbose_name }}:</label>
            <input class="vTextField" id="id_pattern_field" type="text" value="{{ pattern.extracted_elements_type }}" readonly/>
        </div>
    </div>
    <div>
        <h2 style="text-transform: uppercase;">{% trans "Mappings" %}</h2>
        {% for mapping in pattern.mappings.all %}
        <div class="form-row">
            <label for="id_pattern_field">{{ mapping }}:</label>
            <input class="vTextField" id="id_pattern_field" type="text" value="{{ mapping.mapping_value }}" readonly/>
        </div>
        {% endfor %}
    </div>
</fieldset>

ontogen/templates/ontogen/pattern_test.html
{% load i18n static %}
<script src="{% static 'ontogen/tree/res/lib/jquery/jquery.min.js' %}"></script>
<script src="{% static 'ontogen/dynamic-formset.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('#content-main').load('http://localhost:8000/admin/ontogen/pattern/add/')
    })
</script>
<style>

</style>

<div id="content-main"></div>

ontogen/templates/ontogen/permission_error.html
{% load i18n %}
<div class="bot-modal-header">
    <span class="mod-close" id="modal-close">&times;</span>
    <h1>{% trans "You don't have enough permissions to" %} {{ action }}.</h1>
</div>
<div class="submit-row" style="margin: 0">
    <input id="submit-button" type="button" value="Switch to another user" onclick="window.location='{% url 'ontogen:login' %}'" class="default"/>
</div>

ontogen/templates/ontogen/result.html
{% extends 'ontogen/base.html' %}

{% load i18n %}

{% block content %}
{% trans "Back to repository tree" as back_button %}
<div>
    {% if error_message %}
    <h1>{{ error_message }}</h1>
    <div class="submit-row">
        <a href="{% url 'ontogen:index' %}"><input type="button" value="{{ back_button }}" /></a>
    </div>
    {% else %}
    <h1>{% trans "Resulting ontologies" %}</h1>
    <div style='transform: scale(0.65); margin-left: -25%; margin-top: -125px; margin-right: -25%; margin-bottom: -125px;'>
        <iframe id="ontology_frame" class="ontology" src="https://multont.azurewebsites.net/ontogen/task-ontology" frameborder="1"></iframe>
    </div>
    <textarea id="subject-ontology" readonly hidden>{{ subject_ontology }}</textarea>
    <textarea id="applied-ontology" readonly hidden>{{ applied_ontology }}</textarea>
    <div id="ontology-prefix" hidden>[{{ datetime_prefix|date:"SHORT_DATETIME_FORMAT"}}]</div>
    <div class="submit-row">
        <input type="button" value="{% trans "Download subject ontology" %}" id="download-subject" />
        <input type="button" value="{% trans "Download applied ontology" %}" id="download-applied" />
        <a href="{% url 'ontogen:index' %}"><input type="button" value="{{ back_button }}" /></a> 
    </div>
    {% endif %}
</div>
{% endblock %}

{% block head %}
<style>
    .ontology {
        width: 100%;
        min-height: 100vh;
        resize: none;
        margin: 1em 0;
        box-sizing: border-box;
    }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        function saveTextAsFile(prefix) {
            var textToWrite = document.getElementById(prefix + "-ontology").value;
            var textFileAsBlob = new Blob([textToWrite], { type: 'text/plain' });
            var fileNameToSaveAs = $("#ontology-prefix").text() + " " + prefix + "-ontology.ont";
            var downloadLink = document.createElement("a");

            downloadLink.download = fileNameToSaveAs;
            downloadLink.innerHTML = "My Hidden Link";
            window.URL = window.URL || window.webkitURL;
            downloadLink.href = window.URL.createObjectURL(textFileAsBlob);
            downloadLink.onclick = destroyClickedElement;
            downloadLink.style.display = "none";
            document.body.appendChild(downloadLink);
            downloadLink.click();
        }

        function destroyClickedElement(event) {
            document.body.removeChild(event.target);
        }

        $("#download-subject").click(function (e) {
            e.preventDefault();
            saveTextAsFile("subject");
        });

        $("#download-applied").click(function (e) {
            e.preventDefault();
            saveTextAsFile("applied");
        });
    });

    window.onload = function () {
        if (window.addEventListener) {
            window.addEventListener("message", listener);
        } else {
            // IE8
            window.attachEvent("onmessage", listener);
        }
    }

    function listener(event) {
        if (event.data.fnc == 'OnInitiated') {
            OnInitiated();
        }
    }

    function OnLoadFrame() {
        var snd = {
            'fnc': "DoLoadOwl",
            'ont': '{{ ontology|safe }}',
            'name': 'subject-ontology.ont'
        }

        window.frames[0].postMessage(snd, '*');
        $('#ontology_frame').removeAttr('hidden');
    }

    function OnInitiated() {
        Load();
    }

    function Load() {
        var snd = {
            'fnc': 'Reset',
        }
        window.frames[0].postMessage(snd, '*');
        var millisecondsToWait = 500;
        setTimeout(function () {
            OnLoadFrame();
        }, millisecondsToWait);
    } 
</script>
{% endblock %}

ontogen/templates/ontogen/result_new.html
{% extends 'ontogen/base.html' %}

{% load i18n %}
{% load static %}

{% block content %}
{% trans "Back to repository tree" as back_button %}

{% if error_message %}
<h1>{{ error_message }}</h1>
<div class="submit-row">
    <a href="{% url 'ontogen:index' %}"><input type="button" value="{{ back_button }}" /></a>
</div>
{% else %}
<h1>{% trans "Resulting ontologies" %}</h1>

<div class="ontologies-wrapper">
    <div class="left-ontology">
        <div id="subject-ontology-vis" class="vis"></div>
        <span>{% trans "Subject ontology" %}</span>
    </div>
    <div class="right-ontology">
        <div id="task-ontology-vis" class="vis"></div>
        <span>{% trans "Task ontology" %}</span>
    </div>
</div>

<textarea id="subject-ontology" readonly hidden>{{ subject_ontology }}</textarea>

<!-- TODO fix ontology name -->
<textarea id="task-ontology" readonly hidden>{{ applied_ontology }}</textarea> 

<div id="ontology-prefix" hidden>[{{ datetime_prefix|date:"SHORT_DATETIME_FORMAT"}}]</div>
<div class="submit-row">
    <input type="button" value="{% trans "Download subject ontology" %}" id="download-subject" />
    <input type="button" value="{% trans "Download task ontology" %}" id="download-task" />
    <a href="{% url 'ontogen:index' %}"><input type="button" value="{{ back_button }}" /></a> 
</div>
{% endif %}

{% endblock %}

{% block head %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis.min.js"></script>
<script type="text/javascript" src="{% static "ontogen/ontology/visualize.js" %}"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis.min.css">
<link rel="stylesheet" href="{% static "ontogen/ontology/style.css" %}">

<script>
    $(document).ready(function () {
        function saveTextAsFile(prefix) {
            var textToWrite = document.getElementById(prefix + "-ontology").value;
            var textFileAsBlob = new Blob([textToWrite], { type: 'text/plain' });
            var fileNameToSaveAs = $("#ontology-prefix").text() + " " + prefix + "-ontology.ont";
            var downloadLink = document.createElement("a");

            downloadLink.download = fileNameToSaveAs;
            downloadLink.innerHTML = "My Hidden Link";
            window.URL = window.URL || window.webkitURL;
            downloadLink.href = window.URL.createObjectURL(textFileAsBlob);
            downloadLink.onclick = destroyClickedElement;
            downloadLink.style.display = "none";
            document.body.appendChild(downloadLink);
            downloadLink.click();
        }

        function destroyClickedElement(event) {
            document.body.removeChild(event.target);
        }

        $("#download-subject").click(function (e) {
            e.preventDefault();
            saveTextAsFile("subject");
        });

        $("#download-task").click(function (e) {
            e.preventDefault();
            saveTextAsFile("task");
        });
        
        initializeOntology('subject-ontology-vis', $('#subject-ontology').text());
        initializeOntology('task-ontology-vis', $('#task-ontology').text());
    });
</script>
{% endblock %}

ontogen/templates/ontogen/test.html
<iframe id="subject_ontology_frame" class="ontology" src="https://multont.azurewebsites.net/ontogen/applied_ontology" frameborder="1"></iframe>